name: "Sphinx docs to gh-pages"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64

    - name: Install Nox
      run: pip install nox==2021.6.12

    - name: Install Poetry
      run: pip install poetry==1.1.8

    - name: Build docs
      run: nox -s docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
